apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: rules-api
  name: rules-api
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  selector:
    io.kompose.service: rules-api
status:
  loadBalancer: {}
