version: '3'

services:
  rules-api:
    # image: 'rules-api'
    image: 'localhost:5000/rules-api'
    build:
      context: .
    working_dir: /usr/src/app
    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"
    # volumes:
    #   - .:/usr/src/app
    command: node dist/index
    restart: always
    depends_on:
      - mongo
    # Overwrite any env var defined in .env file (if required)
    environment:
      - MONGO_HOST=mongodb://mongo/express-mongoose-es6-rest-api-development
      - DEBUG=express-mongoose-es6-rest-api:*
      - NODE_ENV=development
      - PORT=4040
      - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      - MONGO_PORT=27017
    # Link to containers in another service.
    # Links also express dependency between services in the same way as depends_on,
    # so they determine the order of service startup.
  # mongo:
  #   image: "mongo:3.4.2"
  #   ports:
  #     - "27017:27017"
